### ISSUE TITLE
configure *.h5 files' location

### ISSUE THREAD

**Issue by schermannj** [stevengj/mpb#12]
Hi, Is it possible to configure *.h5  files location when I run `mpb /home/user/mpb/input.ctl > /home/user/mpb/output.out`? I'm asking because mpb saves files to `/home/user/`. 
I'm using mpb 1.4.2. I didn't found it a solution in your documentation, maybe I missed it, but it will be very cool if you'll help me with this issue.

**Comment by stevengj** [comment]
It outputs to the current directory.  Just change directories to where you want the output:
```
cd /my/output/directory
mpb /home/user/mpb/input.ctl > /home/user/mpb/output.out
```
