### ISSUE TITLE
configure script fails on macOS Sierra 

### ISSUE THREAD

**Issue by JohnWeiner** [stevengj/mpb#20]
While trying to configure mpb-1.5 with
```
./configure -v LIBS=-ldl LDFLAGS=-L/usr/local/opt/fftw/lib-L/usr/local/lib CPPFLAGS=-I/usr/local/opt/fftw/include-I/usr/local/include
```
the script exits with

configure:16941: error: The FFTW libraries could not be found.  Make sure FFTW is installed, and that LDFLAGS and CPPFLAGS are set appropriately if necessary.

fftw was installed with home-brew which puts symbolic links in /usr/local/opt/fftw.  The libraries appear to be where they are supposed to be.  The only other error message generated by the configure script was 
conftest.c:11:10: fatal error: 'ac_nonexistent.h' file not found.

I don't know what conftest.c does (I presume it is a configuration test), but whatever it does it appears to be missing a header file.  I don't know if conftest.c is relevant to the problem of the configure script not being able to find the fftw libraries.

I have also done 
export LDFLAGS=/usr/local/lib:/usr/local/opt/fftw/lib and similarly for CPPFLAGS.  
All to no avail.

cat config.log|grep warning shows
ld: warning: directory not found for option '-L/usr/local/lib-L/usr/local/opt/fftw/lib'

ld cannot find these directories that certainly do exist.

**Comment by stevengj** [comment]
You are missing quotes and spaces:
```
./configure -v LIBS=-ldl LDFLAGS="-L/usr/local/opt/fftw/lib -L/usr/local/lib" CPPFLAGS="-I/usr/local/opt/fftw/include -I/usr/local/include"
```
