### ISSUE TITLE
Configure script does not fail on macOS Sierra

### ISSUE THREAD

**Issue by JohnWeiner** [stevengj/mpb#21]
Yesterday's problem has been resolved.  The configure script will run properly with:

export LDFLAGS=-L/usr/local/lib
export CPPFLAGS=-I/usr/local/include

There is no need to try to add the path /usr/local/opt/fftw/lib to the LDFLAGS or the analogous path to .../include for CPPFLAGS. Attempting to do so results in the error described in issue #20

**Comment by stevengj** [comment]
Great.
