### ISSUE TITLE
CHECK failure on line 420 of matrixio.c: no matrixio implementation is linked

### ISSUE THREAD

**Issue by ratcoder** [stevengj/mpb#28]
When using diamond.ctl from examples, when using command
`mpb-data -m 2 -r -n 32 epsilon.h5 dpwr.k06.b*.h5`

> the error CHECK failure on line 420 of matrixio.c: no matrixio implementation is linked

 is encountered.

**Comment by stevengj** [comment]
You need to make sure that MPB is compiled with HDF5.

**Comment by cgaravitoc** [comment]
> You need to make sure that MPB is compiled with HDF5.

How can I do that?
I have the same problem!

Thanks!

**Comment by ChristopherHogan** [comment]
You need to tell MPB where to find the HDF5 library. If you're on Ubuntu, APT will install the headers in `/usr/include/hdf5/<serial | openmpi>` (depending on whether you installed the serial or mpi version), and the shared library is in `/usr/lib/x86_64-linux-gnu/hdf5/<serial | openmpi>`. You should add these paths to your include and library search paths via `CPPFLAGS` and `LDFLAGS`. There is an example in the [documentation](https://mpb.readthedocs.io/en/latest/Installation/#python) (you can ignore the Python specifics if you're only interested in the Scheme interface).

**Comment by cgaravitoc** [comment]
Thank you for the quick response!

I am running ubuntu and I installed mpb using 'sudo apt-get install'. I searched for the paths that you mention: `/usr/include/hdf5/` and `/usr/lib/x86_64-linux-gnu/hdf5/` but they does not appear on my computer. I tried to install hdf5 in a similar way using 'sudo apt-get install' but on terminal appears the following message `Unable to locate package hdf5`. So, I must install hdf5 from source? 

Thanks again!!!

**Comment by ChristopherHogan** [comment]
The installation command is
```sh
$ sudo apt-get install libhdf5-dev
```
I don't know if the MPB package will automatically find hdf5 since you installed hdf5 after MPB. You may have to reinstall MPB.

**Comment by cgaravitoc** [comment]
I uninstall mpb with `sudo apt-get remove mpb && apt autoremove && apt purge & sudo apt clean`. Later, I install the package on the way that you sugest with `sudo apt-get install libhdf5-dev`. Hence, I install again mpb again with `sudo apt-get install mpb`. However, when I try to reproduce the [Tri-rods Dielectric function](https://mpb.readthedocs.io/en/latest/Data_Analysis_Tutorial/#the-tri-rods-dielectric-function) example, evaluating on terminal the line ` mpb-data -r -m 3 -n 32 epsilon.h5`, it shows me the following error: `CHECK failure on line 420 of matrixio.c: no matrixio implementation is linked`. After the procedure that you recomend to fix the error, the error is still appearing. What other solution do you recomend to implement?

**Comment by ChristopherHogan** [comment]
I just installed MPB via APT on a clean Ubuntu 16.04 and everything worked fine. Perhaps the issue is that the docs specify `epsilon.h5` but the actual file has the script name prepended - `tri-rods-epsilon.h5`. Here's what worked for me.
```sh
$ sudo apt-get install mpb
$ mpb tri-rods.ctl >& tri-rods.out
$ mpb-data -r -m 3 -n 32 tri-rods-epsilon.h5
```

**Comment by cgaravitoc** [comment]
I realized about the prefix on `epsilon.h5` file. But is still not working. The same error is showing. My last attempt is going to restart ubuntu and reinstall, first `libhdf5-dev` and later `mpb`. 

Thanks for your time!

**Comment by cgaravitoc** [comment]
Hi!

I just want to tell you that I installed `libhdf5-dev` and later `mpb` via `apt-get` on a different notebook with Debian 9 OS and the error is not present. Thanks!
