### ISSUE TITLE
"Error while loading shared libraries: libopenblas.dll" while opening mpb.

### ISSUE THREAD

**Issue by hatred-oberon** [stevengj/mpb#3]
$ mpb
/usr/local/bin/mpb.exe: error while loading shared libraries: libopenblas.dll: cannot open shared object file: No such file or directory

Can you help me with my problem? Here is my system info:

$ uname -a
CYGWIN_NT-6.3-WOW64 Oberon 1.7.33-2(0.280/5/3) 2014-11-13 15:45 i686 Cygwin

**Comment by hatred-oberon** [comment]
I don't get an error only when i put libopenblas.dll into cygwin/bin, but when i am trying to do
mpb tutorial.ctl > 1.out
the .out file is empy(
And when i an trying to invoke mpb with no arguments, i am not dropping into an interactive mode(

**Comment by hatred-oberon** [comment]
Oh, problem was so simpe)
I have just compiled all libraries (BLAS, LAPACK, FFTW, libctl) on my own with the same Fortran compiler and everything started working.

**Comment by stevengj** [comment]
Glad it is working now!  Yes, you have to be consistent about compilers, unfortunately.
