### ISSUE TITLE
error " no such file or directory" 

### ISSUE THREAD

**Issue by vahidehnodehi** [stevengj/mpb#32]
Hello,

Is there anybody who can help me with a problem. I need to calculate DOS of a diamond structure using the diamond.ctl at the example. I do as follow:

    mpb diamond.ctl >& diamond.out
    mpb include dos.scm
    but after this I got this error:
    " Backtrace:
    In ice-9/boot-9.scm:
    160: 4 [catch #t #<catch-closure 563db32de620> ...]
    In unknown file:
    ?: 3 [apply-smob/1 #<catch-closure 563db32de620>]
    In ice-9/eval.scm:
    432: 2 [eval # #]
    432: 1 [eval # #]
    In unknown file:
    ?: 0 [primitive-load "include"]

ERROR: In procedure primitive-load:
ERROR: In procedure open-file: No such file or directory: "include"
"

I really appreciate it if you let me know what is the problem. even I have tried different notation with (, ' ," .
but it did not work yet.

**Comment by stevengj** [comment]
You would add `include("dos.scm")` to the end of the `diamond.ctl` file and add a call to the `print-dos` function.  You don't run `mpb include dos.scm`.

**Comment by vahidehnodehi** [comment]
Thanks for your reply :).
Regards

**Comment by stevengj** [comment]
Why are your reading `diamond.dat`?

 Just add two lines
```
(include "dos.scm")
(print-dos 0 1 100)
```
to the end of diamond.ctl, and do `mpb diamond.ctl`.

**Comment by stevengj** [comment]
Note, however, that the diamond.ctl file as-is will not give you a good approximation for the DOS; you need to add more k-points to properly sample the whole irreducible Brillouin zone.

See also https://github.com/boyuanliuoptics/DOS-calculation more more efficient code to calculate the DOS.

**Comment by vahidehnodehi** [comment]
I dont know what is the problem. when I add include dos.scm there is no error. But when I add (print-dos 0 1 100) there is an error. I have tried without brackets as well but not working yet. 
you are right the number of points is quite low to get a acceptable DOS. 
Thanks for the link about DOS. the figure looks fabulous if I could acquired the same!!

**Comment by vahidehnodehi** [comment]
Thanks a lot. I have increased the number of points. I have provided dos using those two lines. Also grep dos to get the data. The data looks has two columns. To draw the data what should I do with column 1? because it is like 1/99 23/70 and such data.
