### ISSUE TITLE
material-func does not take µ values

### ISSUE THREAD

**Issue by LingLuIOP** [stevengj/mpb#39]
Dear Steven,

I found that geometries defined by material-func is not compatible with the \mu material definition.
All materials defined this way have \mu = 1.

**Comment by stevengj** [comment]
You currently have to have at least one actual object in the geometry with µ≠1, otherwise it ignores µ.   That object can be zero size, or hidden behind another object.

I should probably add an `extra-materials` variable like in Meep.

**Comment by stevengj** [comment]
Actually, I forgot, there is an input variable `force-mu?`.  So, if you return `mu` from a material function, you should do
```scm
(set! force-mu? true)
```
to tell MPB that you need µ support.

**Comment by stevengj** [comment]
(The Python interface, in stevengj/meep#222, is similar.)

**Comment by LingLuIOP** [comment]
indeed, problem solved. Thank you!
