### ISSUE TITLE
diamond.ctl file

### ISSUE THREAD

**Issue by vahidehnodehi** [stevengj/mpb#40]
Dear mpb users

I was wondering if mpb is able to calculate angle- dependence bandstructure or not? for example at diamond.ctl file, is it possible to calculate the bandstructure when the incident light in air is at 50 degrees?

Cheers

**Comment by stevengj** [comment]
A given incidence angle, for a given termination of the crystal, corresponds to a particular set of k vectors.  (See the section on refraction in chapter 10 of http://ab-initio.mit.edu/book/).   MPB can calculate the band structure for any k vectors you want, so yes.
