### ISSUE TITLE
Eigen mode calculation for 3D

### ISSUE THREAD

**Issue by rchge** [stevengj/mpb#46]
Dear MPB users,

I am fresh to MPB (just a few weeks). When I am trying to calculate the band-structure of 3D lattice with different lattice constants ax=ay=14*az, I just could not get the result as expected (such as a band-gap in z direction); but I could not figure out what is the mistake in the code (attached at the end).

Basically, I am looking at a bragg-graded cylindrical fiber in z direction with perimittivity,  1 + epsilon_1 - epsilon_2*cos(2*beta*z), and radius 5 \mu m, with beta = 4 \mu m^-1; and 3D lattice is obtained by a 2D square stack of the cylindrical fibers in x-y plane with ax=ax=14*pi/4.

Thanks  
-----------------------------code----------------------------------------------------------------------------------------------
import math
import meep as mp
from meep import mpb

# this is the structure for the bragg-graded optical fiber
pi = math.pi
scalratio = 4/pi    # redefine of the unit
#lac = pi/wavecon
htenlac = 1/20     # here we use 10 layer
tenlac = 2*htenlac   # thickness of the layer

geometry_lattice = mp.Lattice(
    basis_size=mp.Vector3(14,14,1),
    basis1=mp.Vector3(1,0,0),
    basis2=mp.Vector3(0,1,0),
    basis3=mp.Vector3(0,0,1)
)

vlist = [
mp.Vector3(0,0,0),
mp.Vector3(0,0,0.5)
]

k_points = mp.interpolate(20,vlist)

eps1 = math.pow((1+1.12),2)-1
eps2 = 0.2
r = 5*scalratio

diel1 = mp.Medium(epsilon=1+(eps1-eps2))
diel2 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*tenlac)))
diel3 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*2*tenlac)))
diel4 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*3*tenlac)))
diel5 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*4*tenlac)))
diel6 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*5*tenlac)))
diel7 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*6*tenlac)))
diel8 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*7*tenlac)))
diel9 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*8*tenlac)))
diel10 = mp.Medium(epsilon=1+(eps1-eps2*math.cos(2*pi*9*tenlac)))

geometry = [mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,0.5*tenlac),material=diel1),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,1.5*tenlac),material=diel2),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,2.5*tenlac),material=diel3),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,3.5*tenlac),material=diel4),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,4.5*tenlac),material=diel5),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,-4.5*tenlac),material=diel6),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,-3.5*tenlac),material=diel7),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,-2.5*tenlac),material=diel8),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,-1.5*tenlac),material=diel9),
            mp.Cylinder(radius=r,axis=mp.Vector3(0,0,1),height=tenlac,center=mp.Vector3(0,0,-0.5*tenlac),material=diel10)]

resolution = 64
mesh_size = 3
num_bands = 20

ms = mpb.ModeSolver(
    geometry_lattice=geometry_lattice,
    k_points=k_points,
    geometry=geometry,
    resolution=resolution,
    num_bands=num_bands,
    mesh_size=mesh_size
)

ms.run(mpb.output_at_kpoint(mp.Vector3(0, 0, 0.5), mpb.output_dpwr))

**Comment by stevengj** [comment]
Make sure you plot the resulting `epsilon` to make sure that the structure is what you think it is.
