### ISSUE TITLE
mpb

### ISSUE THREAD

**Issue by Saranyanarayanan** [stevengj/mpb#54]
I have already installed MPB with out HDF5. But now I want install HDF5. But i could not find any configure file. Can I run MPB and get all data without HDF5?

**Comment by stevengj** [comment]
You need to recompile without HDF5 if you want to output field data to files.  (Or you can use the Python interface and get the data in Python as a numpy array.  But if you can't figure out how to recompile MPB with HDF5 you'll probably have an even harder time compiling with Python.)

**Comment by Saranyanarayanan** [comment]
Thank you Sir. I'll try to install HDF.
