### ISSUE TITLE
make error: No rule to make target `sphere-quad.h', needed by `all'.

### ISSUE THREAD

**Issue by fwang88** [stevengj/mpb#6]
Hi Steven,

I tried to install mpb on a linux system. "./configure" is successful but "make" doesn't go through and I got the following err message:

make  all-recursive
make[1]: Entering directory `/home/fwang/mpb'
Making all in src
make[2]: Entering directory `/home/fwang/mpb/src'
make  all-recursive
make[3]: Entering directory `/home/fwang/mpb/src'
Making all in util
make[4]: Entering directory `/home/fwang/mpb/src/util'
make[4]: *** No rule to make target `sphere-quad.h', needed by `all'.  Stop.
make[4]: Leaving directory `/home/fwang/mpb/src/util'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/fwang/mpb/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/fwang/mpb/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/fwang/mpb'
make: *** [all] Error 2

**Comment by fwang88** [comment]
Never mind. Problem fixed.
I made a mistake to run both "sh autogen.sh" and "./configure".

**Comment by lxuechao** [comment]
您好，您是怎么解决的？

**Comment by fwang88** [comment]
> 您好，您是怎么解决的？

I think
`sh autogen.sh`
then
`make`
should work just fine.
