### ISSUE TITLE
HDF5

### ISSUE THREAD

**Issue by liuhangphy** [stevengj/mpb#66]
Hi,
I am a newer to MPB. I have a question, how can I input a complicated photonic crystal structure (such as helix) to MPB? If I input it through a HDF5 file, how can I generate the file?
Thanks very much!
Hang

**Comment by stevengj** [comment]
You need to write a function ε(x,y,z), in some programming language, that defines the structure you want.  Either evaluate this on a grid and save to HDF5 or pass it directly to MPB via the `material-function` type.
