### ISSUE TITLE
language used in mpb

### ISSUE THREAD

**Issue by Saranyanarayanan** [stevengj/mpb#67]
Is it necessary to use scheme language when writing a program in MPB? Or can we use some other language like fortran?

**Comment by stevengj** [comment]
You can [now call MPB from Python](https://mpb.readthedocs.io/en/latest/Python_User_Interface/) as well.

(There is also an undocumented C-callable library `libmpb.so`, which in principle you could call from Fortran using [`ISO_C_BINDING`](https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fC_005fBINDING.html), but digging around in undocumented internals is not for the fainthearted.)
