### ISSUE TITLE
mpb 1.5 installation on osx 10.10.4

### ISSUE THREAD

**Issue by ehchen** [stevengj/mpb#7]
It seems when I try to configure MPB, I get the following error, even though I had done "brew install fftw" ran without errors:

configure: error: The FFTW libraries could not be found.  Make sure FFTW is installed, and that LDFLAGS and CPPFLAGS are set appropriately if necessary.

I did in fact set my LDFLAGS and CPPFLAGs before running ./configure:
export LDFLAGS=-L/usr/local/opt/fftw/lib
export CPPFLAGS=-I/usr/local/opt/fftw/include

**Comment by stevengj** [comment]
Look in the `config.log` file for "`-lfftw3`" and see what error is occurring when it tries to link the `libfftw3` library.

**Comment by JohnWeiner** [comment]
I have the same problem two years later, and here is the what one finds:
configure:16663: checking for fftw_execute in -lfftw3
configure:16696: gcc -o conftest -g -O2 -Wall -W -Wbad-function-cast -Wcast-qual -Wpointer-arith -Wcast-align -pedantic -I/usr/local/include-I/usr/local/Cellar/hdf5/1.10.1/include-I/usr/local/opt/fftw/include-I/usr/local/Cellar/fftw/3.3.6-pl2/include -L/usr/local/lib-L/usr/local/Cellar/hdf5/1.10.1/lib-L/usr/local/opt/fftw/lib-L/usr/local/Cellar/fftw/3.3.6-pl2/lib conftest.c -lfftw3  -lm  >&5
ld: library not found for -lfftw3
ac_cv_lib_fftw3_fftw_execute=no

**Comment by stevengj** [comment]
`-I/usr/local/include-I/usr/local/Cellar/hdf5/1.10.1/include-I/usr/local/opt/fftw/include-I/usr/local/Cellar/fftw/3.3.6-pl2/include` is clearly wrong because the `-I` options aren't separated by spaces. See also #20.

Please don't file multiple github issues for the same problem.  Just add additional comments to the original issue as needed.

**Comment by JohnWeiner** [comment]
Thanks and sorry for all the dumb stuff…I am somewhat new at this, and finally it dawned on me about the spaces.  Also, I figured how to edit the original comment to minimize the dumb stuff.  It will get better fairly rapidly, and I will spew less garbage all over GitHub site.

**Comment by stevengj** [comment]
No problem.
