### ISSUE TITLE
inputting k- points

### ISSUE THREAD

**Issue by Saranyanarayanan** [stevengj/mpb#75]
When I went through the program for the calculation of photonic band gap of diamond structure (data analysis tutorial of MPB) I noticed that the k- points that are used:
                               (vector3 0 0.5 0.5)           ; X
			       (vector3 0 0.625 0.375)   ; U
			       (vector3 0 0.5 0)              ; L
			       (vector3 0 0 0)                 ; Gamma
			       (vector3 0 0.5 0.5)           ; X
			       (vector3 0.25 0.75 0.5)    ; W
			       (vector3 0.375 0.75 0.375) ; K
But when I searched in literature found that there is a small difference in the k-points:
                               (vector3 0.5 0 0.5)              ; X
			       (vector3 0.625 0.25 0.625) ; U
			       (vector3 0.5 0.5 0.5)           ; L
			       (vector3 0 0 0)                    ; Gamma
			       (vector3 0.5 0 0.5)              ; X
			       (vector3 0.5 0.25 0.75)       ; W
			       (vector3 0.375 0.375 0.75) ; K
[High-throughput electronic band structure calculations:
challenges and tools, Wahyu Setyawan and Stefano Curtarolo]
I run the program with both the set of k-points and the gap i obtained is 10.869% and 11.0109% respectively.
Why is it so?

**Comment by stevengj** [comment]
You have to be careful of the basis; the k points in MPB are specified in the basis of the *primitive* reciprocal lattice vectors, not in the Cartesian basis (i.e. not in the basis of the reciprocal lattice vectors of the cubic supercell).

**Comment by stevengj** [comment]
For example, if we look at the L point:
```
mpb> (set! geometry-lattice (make lattice 
                         (basis-size (sqrt 0.5) (sqrt 0.5) (sqrt 0.5))
                         (basis1 0 1 1)
                         (basis2 1 0 1)
                         (basis3 1 1 0)))
mpb> (reciprocal->cartesian (vector3 0 0.5 0))
$1 = #(0.5 -0.5 0.5)
```
we see that in Cartesian coordinates MPB's L point is (0.5,-0.5,0.5), which is the same as the one you quote above (up to a reflection).
