### ISSUE TITLE
Operator Formulation for Lossy Materials

### ISSUE THREAD

**Issue by smartalecH** [stevengj/mpb#77]
Does MPB cite any papers that describe how it formulates and discretizes its operator of which it finds the eigenvalues?

Several papers take common Maxwell operator formulations and "upgrade" them (or modify them) to enable lossy materials or even materials with perfectly matched boundary layers.

**Comment by stevengj** [comment]
This is the paper that describes MPB in detail:

http://www.opticsinfobase.org/abstract.cfm?URI=oe-8-3-173

This is linked in the manual from https://mpb.readthedocs.io/en/latest/Developer_Information/#the-mathematics-of-mpb

In principle, similar techniques can be used for lossy media, with the caveats that:

* Lossy media make the operator non-Hermitian, requiring completely different eigensolver techniques and a different way of describing  the eigenvalues you want.  ("Lowest bands" is not applicable any more.)

* Realistic lossy media are often dispersive, transforming it into a nonlinear eigenproblem.  (Of course, if the frequency dependence is a rational function, you can transform it into a polynomial eigenproblem and from there back into a linear eigenproblem, but it is still messier).

* Weakly lossy materials can often be handled via perturbation theory (with MPB computing the lossless solutions).  Strongly lossly materials like metals really call for a different discretization scheme that can employ nonuniform grids, like FEM or BEM.

**Comment by smartalecH** [comment]
Thank you for your comprehensive response. Sorry, I should have picked up on some of those links from the docs.

Using perturbation theory in conjunction with MPB is an interesting idea. Has anyone done this before?
