### ISSUE TITLE
configure without libctl and guile

### ISSUE THREAD

**Issue by amrit-poudel** [stevengj/mpb#9]
I would like to compile MPB  to use it as a C++ library. However, the configure script keeps throwing guile-not-on-the-path error. 

Is there a  way to compile this library without libctl and guile?

Thanks.

**Comment by stevengj** [comment]
No, not currently.

**Comment by amrit-poudel** [comment]
Thanks for the note. 

While I can look at the source code to run mpb as a C++ library, is there already an example on how to calculate the band structure of photonics crystal using mpb as a C++  library?

**Comment by stevengj** [comment]
Only in the [Meep source code](https://github.com/stevengj/meep/blob/master/src/mpb.cpp).  The usage of MPB as a library is pretty low-level and undocumented; I mainly enabled building of MPB as a library (long after MPB was written) for calling from Meep.

**Comment by amrit-poudel** [comment]
I was looking for something like that. Thanks.

Is there a way to compile meep with mpb?  I could not find anything about mpb on the link below.
http://ab-initio.mit.edu/wiki/index.php/Meep_Installation

**Comment by stevengj** [comment]
I should probably add a section to the Meep installation manual (feel free to file an issue), but if you `configure` Meep on a machine where MPB is already installed in a standard directory like /usr/local/lib (or you can use LDFLAGS and CPPFLAGS to specify additional paths, as described in the "installation paths" section of the manual), then it will automatically compile with MPB.

See also the `eigenmode-source` in the Meep reference manual, which uses MPB.

**Comment by amrit-poudel** [comment]
Does this mean I do not need libtool, guile, libctl etc that were required to configure a standalone mpb?(I use meep as C++ library without guile and libctl).

I went through the source code mpb.cpp, and it appears to me that it will compute one of the eigenmodes of a periodic system and will use that mode as an amplitude of the source in FDTD calculation.

Is it true that I will need to add another function to compute *all (or up to certain energy range)* the eigenmodes if I want to plot the band structure?

Thanks.

**Comment by stevengj** [comment]
What exactly are you trying to do?

If you want to plot band structures, why not run MPB directly?

**Comment by amrit-poudel** [comment]
I was trying to avoid installing libctl and guile before I install MPB, but looks like MEEP needs MPB fully installed, so there is no way around libctl and guile. 

(I can certainly use MPB to plot the band structure after I install libctl and guile)

I will close this issue.

Thanks.
